---
title: "DeGAUSS Container Template"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{DeGAUSS Container Template}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

#### Creating all files needed

Use `dht::use_degauss_container()` to create all of the files needed for a DeGAUSS container.

- Files that **need** to be edited:
  - `entrypoint.R` (contains R code to be run in the container)
  - `README.md` (software documentation and example instructions)

- Files that **may** need to be edited (if any files need to be included in the container):
  - `Dockerfile` (file used to build container)
  - `.dockerignore`

- Files that **do not** need to be edited:
  - `Makefile` (see below for `Make` targets)
  - `test/my_address_file_geocoded.csv` (test input data file)
  - `LICENSE.md` (GPL license)
  - `.github/workflows/build-deply.yaml` (GitHub Actions continuous integration)

#### Using R code and data files inside the container

Edit `entrypoint.R` by replacing the example R code with R code that
completes the specific task to be performed by the container, then run
`renv::init()` to initiate the `renv` framework and create `renv.lock`.
Add any geomarker information and addtional details to `README.md`.

If the container requires any other files (e.g., `.rds` datafiles), edit
`Dockerfile` and `.dockerignore` so that the files are copied to the
container and not ignored by Docker. For example, if we want to use
`geomarker_data.rds`, we would make the following changes in `Dockerfile`:

```sh
    COPY entrypoint.R .
	COPY geomarker_data.rd
```

and in `.dockerignore`:

```sh
    # ignore everything
    **

    # except what we need
    !/renv.lock
    !/entrypoint.R
    !/geomarker_data.rds      # make sure the .rds file is not ignored
```

The rest of the DeGAUSS template files come ready-to-use and do not need
to be edited.

#### Using `make` for interactive development

The `Makefile` defines several useful `make` targets that can be useful when locally developing and testing:

- `make build` will build the current DeGAUSS image and name it
- `make test` will run the container on the included example geocoded CSV file
- `make shell` will run a DeGAUSS command, but start an interactive shell for debugging
- `make clean` is equivalent to `docker system prune -f`, which cleans up any stopped containers or dangling image layers
